version: "3.8"

services:
  backend:
    container_name: backend
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./docker/backend.Dockerfile
    env_file:
      - ./env/backend.env
    volumes:
      - .:/app
    ports:
      - "3000:3000"
