name: Django CI

on:
  push:
    branches: 
    - '**'
  pull_request:
    branches: 
    - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']

    services:
      postgres:
        image: postgres:16.2
        env:
          POSTGRES_USER: aparking
          POSTGRES_PASSWORD: aparking
          POSTGRES_DB: aparking_db
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5    

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
    - name: Run migrations (unnecessary)
      run: |
        cd decide
        python manage.py makemigrations
        python manage.py migrate

  codacy-analysis:
    name: Codacy Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Codacy Analysis
        uses: codacy/codacy-analysis-cli-action@master
        with:
          project-token: ${{ secrets.CODACY_API_TOKEN }}
          upload: true