name: Django CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    services:
      postgres:
        image: postgis/postgis:14-3.4
        env:
          POSTGRES_USER: aparking
          POSTGRES_PASSWORD: aparking
          POSTGRES_DB: aparking_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install OS Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y binutils gdal-bin libgdal-dev libproj-dev libpq-dev build-essential git
          rm -rf /var/lib/apt/lists/*

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set Environment Variables
        run: |
          echo "DJANGO_SECRET_KEY=django-insecure-!eb&x8z=%ac03t5%cs-0+9kk&r%rh%3u#yjsxzt*558c971@&b" >> $GITHUB_ENV
          echo "DJANGO_DEBUG=True" >> $GITHUB_ENV
          echo "DJANGO_SETTINGS_OVERRIDE=AparKing_Backend.docker_settings" >> $GITHUB_ENV

      - name: Run Migrations
        run: |
          python manage.py migrate

      - name: Run Tests
        run: |
          python manage.py test

  codacy-analysis:
    name: Codacy Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Codacy Analysis
        uses: codacy/codacy-analysis-cli-action@master
        with:
          project-token: ${{ secrets.CODACY_API_TOKEN }}
          upload: true
